### ISSUE TITLE
io.js support

### ISSUE THREAD

**Issue by fundon** [jprichardson/node-kexec#13]
iojs/io.js#456

```console
> kexec@0.2.0 install /usr/local/lib/node_modules/6to5/node_modules/kexec
> node-gyp configure build

gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.2
gyp info using node@1.0.1 | darwin | x64
gyp http GET http://nodejs.org/dist/v1.0.1/node-v1.0.1.tar.gz
gyp http 404 http://nodejs.org/dist/v1.0.1/node-v1.0.1.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 404 status code downloading tarball
gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_mod
gyp ERR! stack     at Request.emit (events.js:117:20)
gyp ERR! stack     at Request.onRequestResponse (/usr/local/lib/node_modules/npm/no
gyp ERR! stack     at ClientRequest.emit (events.js:95:17)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:399:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:89:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:290:20)
gyp ERR! stack     at Socket.emit (events.js:95:17)
gyp ERR! stack     at readableAddChunk (_stream_readable.js:143:16)
gyp ERR! stack     at Socket.Readable.push (_stream_readable.js:106:10)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/
gyp ERR! cwd /usr/local/lib/node_modules/6to5/node_modules/kexec
gyp ERR! node -v v1.0.1
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
```

**Comment by jprichardson** [comment]
Hmm... ok. `6to5` is using an old version, but the newest version `1.0.0` should work with one little modfiication... to this line: https://github.com/jprichardson/node-kexec/blob/master/binding.gyp#L6

**Comment by jprichardson** [comment]
Once this https://github.com/creationix/nvm/pull/616 gets pulled in, I can easily download `io.js` and test.

**Comment by jprichardson** [comment]
`nvm` now supports `io.js`. Now I need this: https://github.com/iojs/io.js/issues/433

**Comment by fundon** [comment]
Wow, awesome!
I upgrade nvm.

**Comment by jprichardson** [comment]
Almost got this working with the switch from `node-gyp` to `pangyp`

**Comment by jprichardson** [comment]
Done. https://github.com/jprichardson/node-kexec/releases/tag/1.1.0

**Comment by fundon** [comment]
:+1:

**Comment by bobzoller** [comment]
shouldn't pangyp be in dependencies so the install script can run?  Or is it assumed I'll have pangyp in my top-level dependencies?  I have kexec as a dependency in my package.json and I get the following error on npm install:

```
> kexec@1.1.0 install /Users/bob/Projects/goodeggs-spec-helpers/node_modules/kexec
> pangyp configure build

sh: pangyp: command not found
npm ERR! kexec@1.1.0 install: `pangyp configure build`
npm ERR! Exit status 127
npm ERR!
npm ERR! Failed at the kexec@1.1.0 install script.
npm ERR! This is most likely a problem with the kexec package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     pangyp configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls kexec
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 13.4.0
npm ERR! command "node" "/usr/local/opt/nvm/v0.10.26/bin/npm" "install"
npm ERR! cwd /Users/bob/Projects/goodeggs-spec-helpers
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
```

**Comment by jprichardson** [comment]
Hmm. `pangyp` is a temporary replacement for `node-gyp`... `node-gyp` is used for easy building of native addons. I believe in the ecosystem that it's assumed that anyone that wants to install a native addon should `npm install -g node-gyp` and in this case, `npm install -g pangyp`. 

For example, `fsevents` a popular package does this: https://github.com/pipobscure/fsevents/blob/master/package.json 

Maybe I shouldn't even have `pangyp` as a `devDependency`. 

I'm not sure what to think here. What are other mainstream native packages doing?
