### ISSUE TITLE
npm install fails on windows

### ISSUE THREAD

**Issue by s-a** [jprichardson/node-kexec#19]
```bash
c:\git\electron-recompile\tmp>npm install kexec
-
> kexec@1.2.0 install c:\git\electron-recompile\node_modules\kexec
> pangyp configure build

Das System kann den angegebenen Pfad nicht finden.
gyp: Call to 'node -v |grep "v0.1[12]" > /dev/null && echo "__NODE_GTE_V0_11__" || echo "__NODE_LT_V0_11__"' returned exit status 255. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (c:\git\electron-recompile\node_modules\kexec\node_modules\pangyp\lib\configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "c:\\git\\electron-recompile\\node_modules\\kexec\\node_modules\\pangyp\\bin\\node-gyp.js" "configure" "build"
gyp ERR! cwd c:\git\electron-recompile\node_modules\kexec
gyp ERR! node -v v0.12.6
gyp ERR! pangyp -v v2.3.0
gyp ERR! not ok
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "kexec"
npm ERR! node v0.12.6
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE

npm ERR! kexec@1.2.0 install: `pangyp configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kexec@1.2.0 install script 'pangyp configure build'.
npm ERR! This is most likely a problem with the kexec package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     pangyp configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls kexec
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\git\electron-recompile\tmp\npm-debug.log

c:\git\electron-recompile\tmp>
```

**Comment by jprichardson** [comment]
Yeah, it won't work on Windows since it uses Posix APIs. Happy to accept a PR for it though.

**Comment by timdp** [comment]
Could you add [`"os"`](https://docs.npmjs.com/files/package.json#os) to package.json to avoid installing on Windows? That would make [this babel-cli snippet](https://github.com/babel/babel/blob/01918c68c196b2dd3ab54a20e2598271041fe50a/packages/babel-cli/src/babel-node.js#L75) work, right?

**Comment by jprichardson** [comment]
Sure, would accept a PR.
