### ISSUE TITLE
install fails on node 4.0.0

### ISSUE THREAD

**Issue by coleww** [jprichardson/node-kexec#20]
It looks like pangyp is deprecated in favor of node-gyp? I tried swapping pangyp for node-gyp but ended up with the same error:

```npm WARN deprecated pangyp@2.3.2: use node-gyp@3+, it does all the things
/
> kexec@1.2.0 install /Users/cole/projects/cockney-rhyming-slang/node_modules/kexec
> pangyp configure build

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CXX(target) Release/obj.target/kexec/src/kexec.o
../src/kexec.cc:22:30: error: use of undeclared identifier 'F_GETFD'
    int flags = fcntl (desc, F_GETFD, 0);
                             ^
../src/kexec.cc:26:15: error: use of undeclared identifier 'FD_CLOEXEC'
    flags &= ~FD_CLOEXEC; //clear FD_CLOEXEC bit
              ^
../src/kexec.cc:27:25: error: use of undeclared identifier 'F_SETFD'
    return fcntl (desc, F_SETFD, flags);
                        ^
../src/kexec.cc:43:34: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
static Handle<Value> kexec(const Arguments& args) {
                                 ^~~~~~~~~
                                 v8::internal::Arguments
/Users/cole/.node-gyp/4.0.0/deps/v8/include/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/kexec.cc:44:17: error: calling a protected constructor of class 'v8::HandleScope'
    HandleScope scope;
                ^
/Users/cole/.node-gyp/4.0.0/deps/v8/include/v8.h:885:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../src/kexec.cc:67:19: error: member access into incomplete type 'const v8::internal::Arguments'
    if ( 1 == args.Length() && args[0]->IsString() )
                  ^
/Users/cole/.node-gyp/4.0.0/deps/v8/include/v8.h:139:7: note: forward declaration of 'v8::internal::Arguments'
class Arguments;
      ^
../src/kexec.cc:69:37: error: type 'const v8::internal::Arguments' does not provide a subscript operator
        String::Utf8Value v8str(args[0]);
                                ~~~~^~
../src/kexec.cc:78:44: error: too few arguments to function call, expected 2, have 1
        Local<Number> num = Number::New(err);
                            ~~~~~~~~~~~    ^
/Users/cole/.node-gyp/4.0.0/deps/v8/include/v8.h:2486:3: note: 'New' declared here
  static Local<Number> New(Isolate* isolate, double value);
  ^
../src/kexec.cc:79:22: error: no member named 'Close' in 'v8::HandleScope'
        return scope.Close(num/*Undefined()*/);
               ~~~~~ ^
../src/kexec.cc:83:19: error: member access into incomplete type 'const v8::internal::Arguments'
    if ( 2 == args.Length() && args[0]->IsString() && args[1]->IsArray() )
                  ^
/Users/cole/.node-gyp/4.0.0/deps/v8/include/v8.h:139:7: note: forward declaration of 'v8::internal::Arguments'
class Arguments;
      ^
../src/kexec.cc:85:37: error: type 'const v8::internal::Arguments' does not provide a subscript operator
        String::Utf8Value v8str(args[0]);
                                ~~~~^~
../src/kexec.cc:89:59: error: type 'const v8::internal::Arguments' does not provide a subscript operator
        Local<Array> argv_handle = Local<Array>::Cast(args[1]);
                                                      ~~~~^~
../src/kexec.cc:101:66: error: too few arguments to function call, expected 2, have 1
            String::Utf8Value arg(argv_handle->Get(Integer::New(i))->ToString());
                                                   ~~~~~~~~~~~~  ^
/Users/cole/.node-gyp/4.0.0/deps/v8/include/v8.h:2499:3: note: 'New' declared here
  static Local<Integer> New(Isolate* isolate, int32_t value);
  ^
../src/kexec.cc:118:44: error: too few arguments to function call, expected 2, have 1
        Local<Number> num = Number::New(err);
                            ~~~~~~~~~~~    ^
/Users/cole/.node-gyp/4.0.0/deps/v8/include/v8.h:2486:3: note: 'New' declared here
  static Local<Number> New(Isolate* isolate, double value);
  ^
../src/kexec.cc:119:22: error: no member named 'Close' in 'v8::HandleScope'
        return scope.Close(num/*Undefined()*/);
               ~~~~~ ^
../src/kexec.cc:127:49: error: no member named 'New' in 'v8::String'
    ThrowException(Exception::TypeError(String::New("kexec: invalid arguments")));
                                        ~~~~~~~~^
../src/kexec.cc:128:18: error: no member named 'Close' in 'v8::HandleScope'
    return scope.Close(Undefined());
           ~~~~~ ^
../src/kexec.cc:128:24: error: no matching function for call to 'Undefined'
    return scope.Close(Undefined());
                       ^~~~~~~~~
/Users/cole/.node-gyp/4.0.0/deps/v8/include/v8.h:315:27: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
  friend Local<Primitive> Undefined(Isolate* isolate);
                          ^
../src/kexec.cc:134:9: error: no matching function for call to 'NODE_SET_METHOD'
        NODE_SET_METHOD(target, "kexec", kexec);
        ^~~~~~~~~~~~~~~
/Users/cole/.node-gyp/4.0.0/src/node.h:248:25: note: expanded from macro 'NODE_SET_METHOD'
#define NODE_SET_METHOD node::NODE_SET_METHOD
                        ^~~~~~~~~~~~~~~~~~~~~
/Users/cole/.node-gyp/4.0.0/src/node.h:236:13: note: candidate function [with TypeName = v8::Local<v8::Object>] not viable: no known conversion from 'Handle<v8::Value> (const v8::internal::Arguments &)' to 'v8::FunctionCallback'
      (aka 'void (*)(const FunctionCallbackInfo<v8::Value> &)') for 3rd argument
inline void NODE_SET_METHOD(const TypeName& recv,
            ^
19 errors generated.
make: *** [Release/obj.target/kexec/src/kexec.o] Error 1```

**Comment by jprichardson** [comment]
Not sure. Perhaps @foysavas may know... (assuming he still uses the module)

**Comment by coleww** [comment]
https://github.com/Southern/node-x509/blob/master/.travis.yml 
I found this which seems to fix node-gyp issues with 4.0.0, but it also seems like 4.0.0 just has some issues in general. I'd be happy to make a PR in a few days once the dust has settled. 
I use this module in https://github.com/coleww/mkproj and it is fantastic.

**Comment by foysavas** [comment]
Node v4 uses a new version of V8. You can do the follow:

1. Detect Node v4 and define a constant in the [binding.gyp](https://github.com/jprichardson/node-kexec/blob/master/binding.gyp#L6-L9)

2. Modify [kexec.cc](https://github.com/jprichardson/node-kexec/blob/master/src/kexec.cc) to call the updated V8 functions when compiled for Node v4.

@coleww I'm stuck on Node v0.12 for the time being, so probably best to code it yourself. glhf!

**Comment by ChALkeR** [comment]
Adding to the list: https://github.com/nodejs/node/issues/2798.

**Comment by coleww** [comment]
awesome! thanks for the guidance, working on it

**Comment by jeromemacias** [comment]
Any news about this issue ?

**Comment by jprichardson** [comment]
Published in [1.3.0](https://github.com/jprichardson/node-kexec/releases/tag/1.3.0). Thanks to @foysavas!

**Comment by fzaninotto** [comment]
Thanks for the new release! It now works on OSX, but I can't make it work on Linux (Travis CI):

```
> kexec@1.3.0 install /home/travis/build/XXX/node_modules/kexec
> node-gyp configure build
make[1]: Entering directory `/home/travis/build/XXX/node_modules/kexec/build'
  CXX(target) Release/obj.target/kexec/src/kexec.o
In file included from ../src/kexec.cc:2:0:
/home/travis/.node-gyp/4.1.2/include/node/v8.h:336:1: error: expected unqualified-id before ‘using’
/home/travis/.node-gyp/4.1.2/include/node/v8.h:469:1: error: expected unqualified-id before ‘using’
/home/travis/.node-gyp/4.1.2/include/node/v8.h:852:1: error: expected unqualified-id before ‘using’
../src/kexec.cc:133:23: error: variable or field ‘init’ declared void
../src/kexec.cc:133:23: error: ‘Handle’ was not declared in this scope
../src/kexec.cc:133:36: error: expected primary-expression before ‘>’ token
../src/kexec.cc:133:38: error: ‘target’ was not declared in this scope
../src/kexec.cc:137:5: error: ‘init’ was not declared in this scope
../src/kexec.cc:42:13: warning: ‘void kexec(const v8::FunctionCallbackInfo<v8::Value>&)’ defined but not used [-Wunused-function]
make[1]: *** [Release/obj.target/kexec/src/kexec.o] Error 1
make[1]: Leaving directory `/home/travis/build/XXX/node_modules/kexec/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/travis/.nvm/versions/node/v4.1.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.13.0-40-generic
gyp ERR! command "/home/travis/.nvm/versions/node/v4.1.2/bin/node" "/home/travis/.nvm/versions/node/v4.1.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /home/travis/build/XXX/node_modules/kexec
gyp ERR! node -v v4.1.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Linux 3.13.0-40-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v4.1.2/bin/node" "/home/travis/.nvm/versions/node/v4.1.2/bin/npm" "install"
npm ERR! node v4.1.2
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE
npm ERR! kexec@1.3.0 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the kexec@1.3.0 install script 'node-gyp configure build'.
npm ERR! This is most likely a problem with the kexec package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls kexec
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/XXX/npm-debug.log
```

**Comment by jeromemacias** [comment]
I confirm that https://github.com/jprichardson/node-kexec/issues/22 definitely fixed current issue.
