### ISSUE TITLE
replace node-gyp

### ISSUE THREAD

**Issue by piranna** [jprichardson/node-kexec#23]
By using node-gyp add 9MB of dependencies, that's totally huge. I'm not sure, but maybe nan needs less disk space, and also is now the standard to build Node.js addons.

**Comment by piranna** [comment]
Ok, npm [has it's own copy of node-gyp](https://github.com/nodejs/node-gyp/wiki/Updating-npm's-bundled-node-gyp) and available by default, and in fact [it's updated](https://github.com/npm/npm/blob/master/node_modules/node-gyp/package.json), so I think we can remove that dependency without damage.

**Comment by jprichardson** [comment]
I'm OK with this, what do you think @foysavas?

**Comment by btakita** [comment]
I'm getting the following error when running `npm install kexec`

~~~
$ npm install --save kexec
> kexec@2.0.2 install /home/phoenix/workspace/tenfore-bot/node_modules/kexec
> node-gyp rebuild

Traceback (most recent call last):
  File "/usr/share/node-gyp/gyp/gyp_main.py", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3138, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3124, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3151, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 652, in _build_master
    ws = cls()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 645, in __init__
    self.add_entry(entry)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 701, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2139, in find_on_path
    path_item, entry, metadata, precedence=DEVELOP_DIST
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2521, in from_location
    py_version=py_version, platform=platform, **kw
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2835, in _reload_version
    md_version = _version_from_file(self._get_metadata(self.PKG_INFO))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2486, in _version_from_file
    line = next(iter(version_lines), '')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2654, in _get_metadata
    for line in self.get_metadata_lines(name):
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2030, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2025, in get_metadata
    metadata = f.read()
  File "/usr/lib/python2.7/codecs.py", line 314, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xb6 in position 147: invalid start byte
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:354:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/phoenix/workspace/tenfore-bot/node_modules/kexec
gyp ERR! node -v v4.2.3
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! kexec@2.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the kexec@2.0.2 install script.
npm ERR! This is most likely a problem with the kexec package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls kexec
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "--save" "kexec"
npm ERR! cwd /home/phoenix/workspace/tenfore-bot
npm ERR! node -v v4.2.3
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/phoenix/workspace/tenfore-bot/npm-debug.log
npm ERR! not ok code 0
~~~

**Comment by btakita** [comment]
There was an issue with the debian nodejs package.

Using nodejs from https://nodejs.org/en/ fixed the issue
